version: '3.7'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=musiqueue
      - POSTGRES_PASSWORD=pass
    command: ["postgres", "-c", "log_statement=all"]

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/musiqueue
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass
